services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php-fpm
      - mysql
    links:
      - php-fpm
      - mysql
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - ./certbot/www:/var/www/certbot
  php-fpm:
    image: php:8-fpm
    container_name: php-container
    volumes_from:
      - app-data
    # links:
    #   - nginx
    #   - mysql
  app-data:
    image: php:8-fpm
    container_name: app-data-container
    command: "true"
    volumes:
      - ./src/:/var/www/html/
  mysql:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE : 'testdb'
      MYSQL_USER : 'someus3r'
      MYSQL_PASSWORD: 'ch4ng3_m3'
    volumes:
      - ./mysql_data:/var/lib/mysql
    # links:
    #   - php-fpm
    #   - nginx
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    links:
      - php-fpm
      - mysql
      - nginx
    ports:
      - "8082:80"
    environment:
      MYSQL_USERNAME: 'someus3r'
      MYSQL_PASSWORD: 'ch4ng3_m3'
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
      PMA_HOST: 'mysql-container'
  maildev:
    image: djfarrelly/maildev
    container_name: maildev-container
    ports:
      - "8081:80"
  # node
  #node-service:
  #  image: node:latest
  #  container_name: node-container
  #  volumes:
  #    - ./app:/var/www/project
  #  working_dir: /var/www/project
  #  networks:
  #    - nginx-php74-mysql8-node
